# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"4\n\x04Time\x12\x0c\n\x04hour\x18\x01 \x02(\r\x12\x0e\n\x06minute\x18\x02 \x02(\r\x12\x0e\n\x06second\x18\x03 \x02(\r\"O\n\rSensorReading\x12\x14\n\x0cpublisher_id\x18\x01 \x02(\t\x12\x13\n\x0btemperature\x18\x02 \x02(\x02\x12\x13\n\x04time\x18\x03 \x02(\x0b\x32\x05.Time')



_TIME = DESCRIPTOR.message_types_by_name['Time']
_SENSORREADING = DESCRIPTOR.message_types_by_name['SensorReading']
Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:Time)
  })
_sym_db.RegisterMessage(Time)

SensorReading = _reflection.GeneratedProtocolMessageType('SensorReading', (_message.Message,), {
  'DESCRIPTOR' : _SENSORREADING,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:SensorReading)
  })
_sym_db.RegisterMessage(SensorReading)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIME._serialized_start=16
  _TIME._serialized_end=68
  _SENSORREADING._serialized_start=70
  _SENSORREADING._serialized_end=149
# @@protoc_insertion_point(module_scope)
